### ISSUE TITLE
Platformio compile error - util/delay.h  error

### ISSUE THREAD

**Issue by bjkayani** [adafruit/TinyWireM#17]
- Board:  Adafruit Feather M4
- Plaftformio with RTClib
- Issue: the library is giving a compile error
`.pio\libdeps\adafruit_feather_m4\TinyWireM_ID797\USI_TWI_Master.cpp:23:10: fatal error: util/delay.h: No such file or directory
 #include <util/delay.h>
          ^~~~~~~~~~~~~~`
I have tried the usual suspects but cant figure it out. compiles fine in arduino ide though.

**Comment by ladyada** [comment]
hi this is due to library dependancies that are installed for all platforms even if only one platform needs that library. @ivankravets can help you remove that library from installing.

**Comment by ivankravets** [comment]
Hi all,

Which library should be excluded? @bjkayani , please use https://docs.platformio.org/en/latest/projectconf/section_env_library.html#lib-ignore

**Comment by ladyada** [comment]
this one, TinyWireM, which is only #ifdef'd for ATTINY chips on some sensors

**Comment by bjkayani** [comment]
I got it to compile when I ignored TinyWireM. You guys are amazing. The CEO of platformio and adafruit helping me on my issue. I love this community. Cheers.

**Comment by ivankravets** [comment]
Happy coding with Adafruit and PlatformIO!
